services:
  # Servizio PHP-FPM usato da Apache e Nginx
  php-fpm:
    image: php:8.2-fpm
    volumes:
      - ./fileSorgenti:/var/www/html

  # 1. Server Apache
  apache:
    image: httpd:2.4
    ports:
      - "8080:80"  # Apache sarà accessibile su http://localhost:8080
    volumes:
      - ./fileSorgenti:/usr/local/apache2/htdocs/         # Cartella con file statico e dinamico
      - ./apache/httpd.conf:/usr/local/apache2/conf/httpd.conf # Configurazione personalizzata
    depends_on:
      - php-fpm

  # 2. Server Nginx
  nginx:
    image: nginx:latest
    ports:
      - "8081:80"  # Nginx sarà accessibile su http://localhost:8081
    volumes:
      - ./fileSorgenti:/var/www/html             # Cartella con file statico e dinamico
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf # Configurazione personalizzata
    depends_on:
      - php-fpm

  # 3. Server LiteSpeed (Enterprise Trial)
  litespeed:
    image: litespeedtech/openlitespeed:latest
    ports:
      - "8082:80"  # LiteSpeed sarà accessibile su http://localhost:8082
    volumes:
      - ./fileSorgenti:/var/www/vhosts/localhost/html/      # file statico e dinamico
    environment:
      - TZ=Europe/Rome
